stages:
  - deploy

deploy_to_vps:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh git
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "$SERVER_HOST" >> ~/.ssh/known_hosts
  script:
    - echo "Deploying to $SERVER_HOST..."
    - ssh $SERVER_USER@$SERVER_HOST <<EOF
        set -e
        cd /home/UKMKSR-Website
        git pull origin main
        docker compose down
        docker compose up -d --build
    EOF
  only:
    - main

