name: Build and Deploy to Docker Hub and VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build Docker Image and Push to DockerHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ukmksr-website:latest

  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ukmksr-website:latest
            docker stop laravel_app || true
            docker rm laravel_app || true
            docker run -d \
              --name laravel_app \
              --network laravel_network \
              -v /your/host/path:/var/www/html \
              -p 8080:80 \
              ${{ secrets.DOCKERHUB_USERNAME }}/ukmksr-website:latest